name: Append to release

on:
  release:
    types:
      - "created"

jobs:
  build-kext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.txt"
          # asset_name: test
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
