name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fischerscode/test
          tags: |
            type=raw,prefix=v,value=${{ github.ref }}_${{ github.sha }}
