name: Test

on:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fischerscode/tagger@action-test
        with:
          prefix: v
